import LivePokemon from './LivePokemon'
import ToolWorkspace from './ToolWorkspace'
import MissionTimeline,{type MissionTimelineMission} from './MissionTimeline'
import {useEffect,useState} from 'react'
import './App.css'
import './Office.css'
import './SourceOffice.css'
import './Ecosystem.css'
type Agent={id:number;name:string;family:string;role:string|null;output:string|null}
type Layer={id:string;title:string;content:string;path:string;commit:string}
type Proposal={id:string;path:string;receipt:string|null;observedAt:string;data:Record<string,unknown>}
type Snapshot={available:boolean;error?:string;repository?:string;sha?:string;branch?:string;observedAt:string;files:string[];proposals:Proposal[];sigmaDomains?:{id:string;displayName:string;source:string;sourcePath:string;runtimeFilePresent:boolean}[];tools:{id:string;path:string;available:boolean}[]}
type SharedEntity={id:string;kind:string;label:string;source?:string;sourcePath?:string;runtimeFilePresent?:boolean;domainId?:string;agentId?:string;agentCount?:number;runtimeDeclared?:boolean;sessionId?:string;path?:string;observedAt?:string;gate?:string;reasonCode?:string;severity?:string;decisionAuthority?:string;decisionPhase?:string;targetPath?:string;beforeSha256?:string;afterSha256?:string;status?:string;bytesWritten?:number;recordId?:string;receiptId?:string}
type SharedMission=MissionTimelineMission&{kind:'mission';label:string;domainId:string|null}
type SharedState={schema:string;readonly:boolean;canonicalTruth:boolean;decisionAuthority:string;observedAt:string;entities:SharedEntity[];relations:{from:string;type:string;to:string}[];sessions:{id:string;sessionId:string;agentId:string;name:string;presence:'live'|'unknown'|'ended';phase:string;message:string;objective:string|null;events:{kind:string;phase:string;message:string;timestamp:string;objective?:string;result?:Record<string,unknown>}[]}[];missions:SharedMission[];views:{world:{entityRefs:string[]};workspace:{entityRefs:string[]};pokemon:{entityRefs:string[]}}}
const tools=[['cli','CLI Obsidia'],['brody','Brody'],['obsidure','Obsidure'],['jarjar','Jarjar'],['jarvis','Jarvis']]
export default function Ecosystem(){
 const [view,setView]=useState(location.hash.slice(1)||'agents'),[contextId,setContextId]=useState(sessionStorage.getItem('obsidia-focus-entity')||''),[workspaceArea,setWorkspaceArea]=useState<'home'|'brody'|'obsidure'|'cli'|'files'>((sessionStorage.getItem('obsidia-workspace-area') as 'home'|'brody'|'obsidure'|'cli'|'files')||'home'),[agents,setAgents]=useState<Agent[]>([]),[layers,setLayers]=useState<Layer[]>([]),[snap,setSnap]=useState<Snapshot|null>(null),[shared,setShared]=useState<SharedState|null>(null),[agentId,setAgentId]=useState(1),[project,setProject]=useState(''),[query,setQuery]=useState(''),[document,setDocument]=useState(''),[message,setMessage]=useState(''),[sourceLayer,setSourceLayer]=useState(''),[worldZone,setWorldZone]=useState<'activity'|'agents'|'governance'|'knowledge'|'domains'|'layers'>('activity')
 useEffect(()=>{const abort=new AbortController();const read=async(url:string)=>{const r=await fetch(url,{signal:abort.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()};Promise.all([read('/data/rd-registry.json'),read('/data/obsidia-layers.json')]).then(([a,l])=>{setAgents(a.agents);setLayers(l.layers)}).catch(e=>{if(!abort.signal.aborted)setMessage(String(e))});let pending=false;const refresh=async()=>{if(pending)return;pending=true;try{const [nextSnap,nextShared]=await Promise.all([read('/obsidia-local/snapshot'),read('/obsidia-local/state')]);setSnap(nextSnap);setShared(nextShared)}catch(e){if(!abort.signal.aborted)setMessage(String(e))}finally{pending=false}};void refresh();const timer=setInterval(refresh,5000);const hash=()=>{const next=location.hash.slice(1)||'agents';setView(next);setContextId(sessionStorage.getItem('obsidia-focus-entity')||'');if(next==='workspace'){const area=sessionStorage.getItem('obsidia-workspace-area');if(area==='home'||area==='brody'||area==='obsidure'||area==='cli'||area==='files')setWorkspaceArea(area)}};const context=(e:Event)=>{const id=(e as CustomEvent<string>).detail||sessionStorage.getItem('obsidia-focus-entity')||'';setContextId(id)};window.addEventListener('hashchange',hash);window.addEventListener('obsidia-context',context as EventListener);return()=>{abort.abort();clearInterval(timer);window.removeEventListener('hashchange',hash);window.removeEventListener('obsidia-context',context as EventListener)}},[])
 const current=agents.find(a=>a.id===agentId),families=[...new Set(agents.map(a=>a.family))],projects=[...new Set((snap?.files||[]).map(p=>p.split('/')[0]))],files=(snap?.files||[]).filter(p=>(!project||p.startsWith(project+'/'))&&p.toLowerCase().includes(query.toLowerCase())).slice(0,200),layer=layers.find(l=>l.id===sourceLayer),focusId=contextId,focus=shared?.entities.find(e=>e.id===focusId),focusRelations=shared?.relations.filter(r=>r.from===focusId||r.to===focusId)||[],domains=shared?.entities.filter(e=>e.kind==='domain')||[],decisions=(shared?.entities.filter(e=>e.kind==='decision_record')||[]).slice(-8).reverse(),impacts=(shared?.entities.filter(e=>e.kind==='impact')||[]).slice(-8).reverse(),missions=(shared?.missions||[]).slice(-8).reverse()
 const focusEntity=(id:string)=>{sessionStorage.setItem('obsidia-focus-entity',id);setContextId(id);window.dispatchEvent(new CustomEvent('obsidia-context',{detail:id}));setMessage('Objet partagé sélectionné : '+id)}
 async function open(id:string){setMessage(id==='brody'?'Démarrage de Brody et vérification de son API…':'Ouverture du terminal '+id+'…');try{const r=await fetch('/obsidia-local/open/'+id,{method:'POST'}),d=await r.json();if(!r.ok)throw Error(d.error);sessionStorage.setItem('obsidia-selected-session',d.sessionId);window.dispatchEvent(new CustomEvent('obsidia-session',{detail:d.sessionId}));location.hash='agents';setMessage('Terminal Windows démarré : '+id)}catch(e){setMessage(String(e))}}
 async function readFile(path:string){try{const r=await fetch('/obsidia-local/file?path='+encodeURIComponent(path)),d=await r.json();if(!r.ok)throw Error(d.error);setDocument(path+'\n\n'+d.content)}catch(e){setMessage(String(e))}}
 const contextEntity=shared?.entities.find(e=>e.id===contextId)
 const contextSession=contextEntity?.kind==='session'?shared?.sessions.find(s=>s.id===contextId):contextEntity?.kind==='agent'?shared?.sessions.find(s=>s.agentId===contextEntity.agentId&&s.presence==='live'):shared?.sessions.find(s=>s.sessionId===sessionStorage.getItem('obsidia-selected-session'))
 const contextMission=contextEntity?.kind==='mission'?shared?.missions.find(m=>m.id===contextId):contextSession?shared?.missions.find(m=>m.sessionRefs.includes(contextSession.id)):shared?.missions.find(m=>m.id===contextId)
 const contextAgent=contextSession?.agentId||contextMission?.agentId||contextEntity?.agentId||null
 const contextResultId=contextMission?.resultRefs[contextMission.resultRefs.length-1]||(contextSession?shared?.relations.filter(r=>r.from===contextSession.id&&['PRODUCES_RESULT','PRODUCES_ARTIFACT'].includes(r.type)).slice(-1)[0]?.to:undefined)
 const contextResult=contextResultId?shared?.entities.find(e=>e.id===contextResultId):undefined
 const contextWhat=contextSession?.objective||contextMission?.actionId||contextEntity?.label||'Aucun objet sélectionné'
 const contextState=contextSession?.phase||contextMission?.status||contextEntity?.kind||'—'
 const contextProof=contextMission?.traceabilityStatus||'non reliée'
 const switchView=(target:'world'|'workspace'|'agents')=>{if(contextId)sessionStorage.setItem('obsidia-focus-entity',contextId);if(target==='workspace'&&contextSession){const area=contextSession.agentId==='brody'?'brody':contextSession.agentId==='obsidure'?'obsidure':contextSession.agentId==='cli'?'cli':'home';sessionStorage.setItem('obsidia-workspace-area',area)}location.hash=target}
 const contextBridge=<section className="context-bridge"><div className="context-bridge-main"><span className="eyebrow">CONTEXTE ACTIF</span><strong>{contextWhat}</strong></div><div className="context-bridge-facts"><span><small>QUI</small><strong>{contextAgent||'—'}</strong></span><span><small>ÉTAT</small><strong>{contextState}</strong></span><span><small>RÉSULTAT</small><strong>{contextResult?.label||'—'}</strong></span><span><small>PREUVE</small><strong>{contextProof}</strong></span></div><nav className="context-bridge-nav"><button aria-current={view==='world'} onClick={()=>switchView('world')}>Voir dans Monde</button><button aria-current={view==='workspace'} onClick={()=>switchView('workspace')}>Voir dans Workspace</button><button aria-current={view==='agents'} onClick={()=>switchView('agents')}>Voir dans Pokémon</button></nav></section>
 const doors=<div className="organ-doors"><span>Accès transversaux aux outils existants</span>{tools.map(([id,name])=><button key={id} disabled={!snap?.tools.some(t=>t.id===id&&t.available)} onClick={()=>open(id)}>{name}<small>{snap?.tools.some(t=>t.id===id&&t.available)?'Ouvrir le terminal':'Lanceur non disponible'}</small></button>)}</div>
 return <div className="observatory"><header className="obs-header"><a className="brand" href="#world">◈ OBSIDIA<small>MONDE · WORKSPACE · POKÉMON VIEW</small></a><span className="authority">KX108_ONLY</span></header><nav className="view-nav">{[['world','Obsidia Monde'],['workspace','Workspace'],['agents','Pokémon View']].map(([id,label])=><a key={id} href={'#'+id} aria-current={view===id?'page':undefined}>{label}</a>)}<a href="#agents" target="obsidia-pokemon">↗ Pokémon View à côté</a></nav><p className="connection">{snap?.available?`Dépôt local · ${snap.branch} · ${snap.sha?.slice(0,12)}`:'Dépôt local non accessible · sources historiques disponibles'} · suivi runtime dans Pokémon View</p>{message&&<p role="status">{message}</p>}{shared&&<p className="connection">État partagé · {shared.entities.length} entités · {shared.relations.length} relations · {shared.sessions.filter(s=>s.presence==='live').length} session(s) live · {shared.decisionAuthority} · READ_ONLY</p>}{contextBridge}{doors}
 {view==='world'?<section className="world-v2">
<header className="world-v2-header"><div><span className="eyebrow">OBSIDIA MONDE</span><h1>Le monde vivant d’Obsidia</h1><p>Une représentation spatiale des objets réellement observés. Clique une zone pour entrer dedans.</p></div><div className="world-v2-pulse"><strong>{shared?.sessions.filter(s=>s.presence==='live').length||0}</strong><span>activité(s) live</span><small>{shared?.entities.length||0} objets projetés</small></div></header>

<section className="world-map-v2" aria-label="Carte globale Obsidia">
 <div className="world-core"><span>◈</span><strong>OBSIDIA</strong><small>écosystème</small></div>
 <button className={"world-zone zone-activity "+(worldZone==='activity'?'selected':'')} onClick={()=>setWorldZone('activity')}><span>◎</span><strong>Activité</strong><small>{shared?.sessions.filter(s=>s.presence==='live').length||0} live · {missions.length} mission(s)</small></button>
 <button className={"world-zone zone-agents "+(worldZone==='agents'?'selected':'')} onClick={()=>setWorldZone('agents')}><span>◇</span><strong>Agents & organes</strong><small>{shared?.entities.filter(e=>e.kind==='agent').length||0} agent(s)</small></button>
 <button className={"world-zone zone-governance "+(worldZone==='governance'?'selected':'')} onClick={()=>setWorldZone('governance')}><span>⬡</span><strong>Gouvernance & preuves</strong><small>{decisions.length} décision(s) récente(s)</small></button>
 <button className={"world-zone zone-knowledge "+(worldZone==='knowledge'?'selected':'')} onClick={()=>setWorldZone('knowledge')}><span>▥</span><strong>Objets & résultats</strong><small>{shared?.entities.filter(e=>['result','artifact','objective','repository'].includes(e.kind)).length||0} objet(s)</small></button>
 <button className={"world-zone zone-domains "+(worldZone==='domains'?'selected':'')} onClick={()=>setWorldZone('domains')}><span>⌂</span><strong>Domaines</strong><small>{domains.length} territoire(s)</small></button>
 <button className={"world-zone zone-layers "+(worldZone==='layers'?'selected':'')} onClick={()=>setWorldZone('layers')}><span>▤</span><strong>Couches documentaires</strong><small>{layers.length} couche(s)</small></button>
 {shared?.sessions.filter(s=>s.presence==='live').slice(0,6).map((s,i)=><button key={s.sessionId} className={"world-live-token live-"+(i%6)} onClick={()=>{focusEntity('session:'+s.sessionId);setWorldZone('activity')}}><span>●</span><strong>{s.name||s.agentId}</strong><small>{s.phase}</small></button>)}
</section>

<section className="world-zone-explorer">
 <div className="world-zone-title"><div><span className="eyebrow">ZONE OUVERTE</span><h2>{worldZone==='activity'?'Activité':worldZone==='agents'?'Agents & organes':worldZone==='governance'?'Gouvernance & preuves':worldZone==='knowledge'?'Objets & résultats':worldZone==='domains'?'Domaines':'Couches documentaires'}</h2></div><span className="world-depth">MONDE → ZONE → OBJET</span></div>

 {worldZone==='activity'&&<div className="world-object-grid">
  {shared?.sessions.filter(s=>s.presence==='live').map(s=>{const sid='session:'+s.sessionId;const m=shared.missions.find(x=>x.sessionRefs.includes(sid));return <button key={s.sessionId} className="world-object-card live" onClick={()=>focusEntity(m?.id||sid)}><span className="world-object-kind">SESSION LIVE</span><strong>{s.name||s.agentId}</strong><p>{s.objective||s.message||'Travail en cours'}</p><small>{s.phase} · {m?.traceabilityStatus||'preuve non reliée'}</small></button>})}
  {missions.map(m=><button key={m.id} className="world-object-card" onClick={()=>focusEntity(m.id)}><span className="world-object-kind">MISSION</span><strong>{m.actionId}</strong><p>{m.agentId||'agent non relié'}</p><small>{m.status} · {m.traceabilityStatus}</small></button>)}
  {!shared?.sessions.some(s=>s.presence==='live')&&!missions.length&&<p className="muted">Aucune activité réelle observée.</p>}
 </div>}

 {worldZone==='agents'&&<div className="world-object-grid">{shared?.entities.filter(e=>e.kind==='agent').map(a=>{const live=shared.sessions.find(s=>s.agentId===a.agentId&&s.presence==='live');return <button key={a.id} className={"world-object-card "+(live?'live':'')} onClick={()=>focusEntity(live?.id||a.id)}><span className="world-object-kind">{live?'AGENT LIVE':'AGENT'}</span><strong>{a.label}</strong><p>{live?.objective||'Aucune activité live observée'}</p><small>{live?.phase||a.source||'déclaré'}</small></button>})}</div>}

 {worldZone==='governance'&&<div className="world-object-grid">
  {shared?.entities.filter(e=>['decision_record','sealed_receipt','rollback_evidence','impact'].includes(e.kind)).slice(-24).reverse().map(e=><button key={e.id} className="world-object-card" onClick={()=>focusEntity(e.id)}><span className="world-object-kind">{e.kind.replaceAll('_',' ')}</span><strong>{e.label}</strong><p>{e.kind==='decision_record'?(e.gate||'UNKNOWN')+' · '+(e.reasonCode||''):e.targetPath||e.status||''}</p><small>{e.decisionAuthority||e.observedAt||''}</small></button>)}
 </div>}

 {worldZone==='knowledge'&&<div className="world-object-grid">
  {shared?.entities.filter(e=>['repository','objective','result','artifact'].includes(e.kind)).slice(-32).reverse().map(e=><button key={e.id} className="world-object-card" onClick={()=>focusEntity(e.id)}><span className="world-object-kind">{e.kind}</span><strong>{e.label}</strong><p>{e.source||e.path||''}</p><small>{e.sessionId?'lié à '+e.sessionId:''}</small></button>)}
 </div>}

 {worldZone==='domains'&&<div className="world-object-grid">{domains.map(d=>{const count=shared?.relations.filter(r=>r.from===d.id&&r.type==='HAS_AGENT').length||0;const liveCount=shared?.relations.filter(r=>r.type==='RUNS_IN_DOMAIN'&&r.to===d.id&&shared.sessions.some(s=>s.id===r.from&&s.presence==='live')).length||0;return <button className="world-object-card" key={d.id} onClick={()=>focusEntity(d.id)}><span className="world-object-kind">DOMAINE</span><strong>{d.label}</strong><p>{count} agent(s) déclaré(s)</p><small>{liveCount} live · {d.runtimeFilePresent?'runtime présent':'runtime non confirmé'}</small></button>})}</div>}

 {worldZone==='layers'&&<div className="world-object-grid">{layers.map(l=><button className="world-object-card" key={l.id} onClick={()=>{setSourceLayer(l.id);setDocument('')}}><span className="world-object-kind">COUCHE</span><strong>{l.title}</strong><p>{l.path}</p><small>{l.commit.slice(0,12)}</small></button>)}</div>}
</section>

{focus&&<section className="world-focus-v2"><div className="world-focus-head"><div><span className="eyebrow">OBJET DANS LE MONDE</span><h2>{focus.label}</h2><p>{focus.kind} · {focus.id}</p></div><div className="world-focus-actions"><button onClick={()=>switchView('workspace')}>Voir dans Workspace</button><button onClick={()=>switchView('agents')}>Voir dans Pokémon</button></div></div>
 {focus.kind==='mission'&&(()=>{const m=shared?.missions.find(x=>x.id===focus.id);return m?<MissionTimeline mission={m} entities={shared?.entities||[]} onFocus={focusEntity}/>:null})()}
 {focus.kind==='decision_record'&&<p><strong>Gate : {focus.gate||'UNKNOWN'}</strong><br/>Raison : {focus.reasonCode||'non exposée'}<br/>Autorité : {focus.decisionAuthority||'non exposée'}</p>}
 {focus.kind==='impact'&&<p><strong>{focus.targetPath}</strong><br/>Avant : <code>{focus.beforeSha256?.slice(0,16)||'?'}</code><br/>Après : <code>{focus.afterSha256?.slice(0,16)||'?'}</code><br/>Statut : {focus.status||'inconnu'}</p>}
 <details><summary>Relations observées · {focusRelations.length}</summary>{focusRelations.map((r,i)=><p key={i}><code>{r.from}</code> → {r.type} → <code>{r.to}</code></p>)}</details>
</section>}

{worldZone==='layers'&&layer&&<section className="world-layer-reader"><div><span className="eyebrow">COUCHE OUVERTE</span><h2>{layer.title}</h2><p>{layer.path} · {layer.commit.slice(0,12)}</p></div><pre className="source-content">{layer.content}</pre></section>}
<p className="declared">Le Monde projette des objets observés ; il ne crée ni activité ni vérité canonique.</p>
</section>:view==='workspace'?<><section className="workspace-v3">
<header className="workspace-v3-header"><div><span className="eyebrow">WORKSPACE</span><h1>Travail Obsidia</h1><p>Le travail courant au centre. Les outils servent ce travail, ils ne sont plus la navigation principale.</p></div><div className="workspace-v3-status"><strong>{shared?.sessions.filter(s=>s.presence==='live').length||0}</strong><span>session(s) active(s)</span></div></header>
<nav className="workspace-v3-tabs" aria-label="Navigation Workspace">
<button aria-current={workspaceArea==='home'} onClick={()=>{sessionStorage.setItem('obsidia-workspace-area','home');setWorkspaceArea('home')}}>Aujourd'hui</button>
<button aria-current={workspaceArea==='brody'} onClick={()=>{sessionStorage.setItem('obsidia-workspace-area','brody');setWorkspaceArea('brody')}}>Brody</button>
<button aria-current={workspaceArea==='obsidure'} onClick={()=>{sessionStorage.setItem('obsidia-workspace-area','obsidure');setWorkspaceArea('obsidure')}}>Obsidure</button>
<button aria-current={workspaceArea==='cli'} onClick={()=>{sessionStorage.setItem('obsidia-workspace-area','cli');setWorkspaceArea('cli')}}>CLI</button>
<button aria-current={workspaceArea==='files'} onClick={()=>{sessionStorage.setItem('obsidia-workspace-area','files');setWorkspaceArea('files')}}>Fichiers & preuves</button>
</nav>
<main className="workspace-v3-main">
{workspaceArea==='brody'?<ToolWorkspace tool="brody" sessions={shared?.sessions||[]} onSelect={id=>sessionStorage.setItem('obsidia-selected-session',id)}/>:workspaceArea==='obsidure'?<ToolWorkspace tool="obsidure" sessions={shared?.sessions||[]} onSelect={id=>sessionStorage.setItem('obsidia-selected-session',id)}/>:workspaceArea==='cli'?<ToolWorkspace tool="cli" sessions={shared?.sessions||[]} onSelect={id=>sessionStorage.setItem('obsidia-selected-session',id)}/>:workspaceArea==='home'?<section className="workspace-v3-dashboard">
<div className="workspace-v3-focus">
<span className="eyebrow">EN COURS</span>
<h2>Travail actif</h2>
{!shared?.sessions.some(s=>s.presence==='live')&&<div className="workspace-v3-empty"><strong>Rien ne tourne.</strong><p>Lance Brody, Obsidure ou la CLI depuis les accès rapides.</p></div>}
{shared?.sessions.filter(s=>s.presence==='live').map(s=>{const sid='session:'+s.sessionId;const mission=shared.missions.find(m=>m.sessionRefs.includes(sid));const resultRefs=shared.relations.filter(r=>r.from===sid&&['PRODUCES_RESULT','PRODUCES_ARTIFACT'].includes(r.type));const results=resultRefs.map(r=>shared.entities.find(e=>e.id===r.to)).filter(Boolean);return <article key={s.sessionId} className="workspace-v3-session"><div className="workspace-v3-session-head"><div><strong>{s.name||s.agentId}</strong><small>Agent · {s.agentId}</small></div><span>{s.phase}</span></div><h3>{s.objective||'Travail sans objectif observé'}</h3><div className="work-context-grid"><div><small>Contexte</small><strong>{snap?.repository||'Dépôt non observé'}</strong><span>{snap?.branch||'branche inconnue'}</span></div><div><small>Résultat</small><strong>{results.length?results[results.length-1]?.label:'Pas encore produit'}</strong><span>{results.length+' objet(s) lié(s)'}</span></div><div><small>Preuve</small><strong>{mission?mission.traceabilityStatus:'Mission non reliée'}</strong><span>{mission?.primaryBlocker||'Aucun blocker de traçabilité observé'}</span></div></div>{mission&&<MissionTimeline compact mission={mission} entities={shared.entities} onFocus={id=>{focusEntity(id);sessionStorage.setItem('obsidia-workspace-area','files');setWorkspaceArea('files')}}/>}<div className="workspace-v3-actions"><button onClick={()=>{sessionStorage.setItem('obsidia-selected-session',s.sessionId);focusEntity('session:'+s.sessionId);const area=s.agentId==='brody'?'brody':s.agentId==='obsidure'?'obsidure':s.agentId==='cli'?'cli':'home';sessionStorage.setItem('obsidia-workspace-area',area);setWorkspaceArea(area)}}>Continuer le travail</button><a href="#agents" onClick={()=>{sessionStorage.setItem('obsidia-selected-session',s.sessionId);focusEntity('session:'+s.sessionId)}}>Voir l’agent</a><a href="#world" onClick={()=>focusEntity(mission?.id||sid)}>Voir dans le Monde</a></div></article>})}
</div>
<aside className="workspace-v3-rail">
<span className="eyebrow">ACCÈS RAPIDES</span>
<button onClick={()=>{sessionStorage.setItem('obsidia-workspace-area','brody');setWorkspaceArea('brody')}}><strong>Brody</strong><small>Discuter, comprendre, raisonner</small></button>
<button onClick={()=>{sessionStorage.setItem('obsidia-workspace-area','obsidure');setWorkspaceArea('obsidure')}}><strong>Obsidure</strong><small>Donner une mission, auditer, construire</small></button>
<button onClick={()=>{sessionStorage.setItem('obsidia-workspace-area','cli');setWorkspaceArea('cli')}}><strong>CLI Obsidia</strong><small>Contrôle direct</small></button>
<button onClick={()=>{sessionStorage.setItem('obsidia-workspace-area','files');setWorkspaceArea('files')}}><strong>Fichiers & preuves</strong><small>Sources, résultats, tests, receipts</small></button>
</aside>
</section>:<section className="workspace-v3-files">
<div className="workspace-v3-files-head"><div><span className="eyebrow">FICHIERS & PREUVES</span><h2>Ce que le travail produit</h2></div><div className="office-toolbar"><select aria-label="Dossier du projet" value={project} onChange={e=>{setProject(e.target.value);setDocument('')}}><option value="">Dépôt entier</option>{projects.map(p=><option key={p}>{p}</option>)}</select><input aria-label="Rechercher les fichiers" placeholder="Rechercher" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>
{focus&&<section className="workspace-v3-focus-object"><span className="eyebrow">OBJET OUVERT</span><h3>{focus.label}</h3><p>{focus.kind} · {focus.id}</p>{focus.kind==='mission'&&(()=>{const m=shared?.missions.find(x=>x.id===focus.id);return m?<MissionTimeline mission={m} entities={shared?.entities||[]} onFocus={focusEntity}/>:null})()}<div className="office-toolbar"><a href="#world">Voir dans le Monde</a><a href="#agents">Voir dans Pokémon</a></div></section>}
<div className="workspace-v3-files-grid"><section><h3>Fichiers</h3><div className="file-list">{files.map(p=><button key={p} onClick={()=>readFile(p)}>{p}</button>)}</div></section><section><h3>Résultats / receipts</h3><button onClick={async()=>{try{const r=await fetch('/obsidia-local/reports');const d=await r.json();setDocument('Rapports des essais live\n\n'+JSON.stringify(d.reports,null,2))}catch(e){setMessage(String(e))}}}>Ouvrir les rapports live</button>{!snap?.proposals.length&&<p>Aucun résultat observé.</p>}{snap?.proposals.map(p=><div key={p.id} className="workspace-v3-result"><button onClick={()=>readFile(p.path)}>{p.id}</button>{p.receipt&&<button onClick={()=>readFile(p.receipt!)}>Receipt</button>}</div>)}</section></div>
{document&&<pre className="source-content workspace-document">{document}</pre>}
</section>}
</main></section></>:<><LivePokemon/><details className="inventory-panel"><summary>Registre historique — 52 agents / neuf familles</summary><h1>Registre R&D</h1><p>52 noms, neuf familles, retrouvés dans l’audit du 12 septembre. Les contrats complets et les affectations actuelles restent à vérifier.</p><main className="office-main"><section className="spatial-map"><div className="rooms">{families.map(f=><section className="room" key={f}><div className="room-sign"><h2>{f}</h2></div><div className="room-floor">{agents.filter(a=>a.family===f).map(a=><button className={`agent-token ${agentId===a.id?'focused':''}`} key={a.id} onClick={()=>setAgentId(a.id)}><span className="pixel-sprite" aria-hidden="true"/><strong>{a.name}</strong><small>Activité non observée</small></button>)}</div></section>)}</div></section><aside className="agent-inspector"><span className="eyebrow">AGENT OBSIDIA / #{current?.id}</span><h2>{current?.name}</h2><p>{current?.family}</p><h3>Fonction source</h3><p>{current?.role||'Le relevé historique fournit le nom, sans contrat détaillé.'}</p><h3>Sortie</h3><p>{current?.output||'Non établie par la source retrouvée'}</p><p>Mission, machine, état, échanges : non observés.</p><p>Autorité : NONE · moteur interchangeable.</p><p className="declared">Source : audit historique du 12 septembre 2026. Rôles des cinq fondateurs : agents/registry.json, commit 13964f05.</p><a href="#workspace">Ouvrir le Workspace</a><details><summary>Méthode de construction</summary><p>Domaine → fonction → contrats d’entrée/sortie → frontières → evidence → choix du moteur → tests → gouvernance X-108.</p></details></aside></main></details></>}
 <footer className="office-footer">Un même écosystème · plusieurs vues<span>Population historique / fichiers locaux observés / sessions observées dans Pokémon View</span></footer></div>
}
