import {useEffect,useState} from 'react'
type Layer={id:string;content:string;path:string;commit:string}
type Organ={name:string;role:string;status:string}
type Definition={title:string;source:string;body:string}
export default function ResearchOffice(){
 const [layers,setLayers]=useState<Layer[]>([]),[definition,setDefinition]=useState<Definition|null>(null),[selected,setSelected]=useState('Brody'),[error,setError]=useState('')
 useEffect(()=>{const c=new AbortController();Promise.all([fetch('/data/obsidia-layers.json',{signal:c.signal}).then(r=>{if(!r.ok)throw Error('Catalogue indisponible');return r.json()}),fetch('/data/agentic-definitions.json',{signal:c.signal}).then(r=>{if(!r.ok)throw Error('Définition indisponible');return r.json()})]).then(([catalogue,doc])=>{setLayers(catalogue.layers);setDefinition(doc)}).catch(e=>{if(!c.signal.aborted)setError(String(e))});return()=>c.abort()},[])
 const source=layers.find(l=>l.id==='10_COGNITIVE_SYSTEM')
 const line=source?.content.split('\n').find(l=>l.includes('Registry des agents de couche :'))
 const names=line?.split('Registry des agents de couche :')[1]?.trim().replace(/\.$/,'').split(',').map(x=>x.trim()).filter(Boolean)||[]
 const organs:Organ[]=source?[{name:'Brody',role:'Comprend, contextualise, relie et décompose ; formule une réponse à partir des sources locales.',status:'Fonction décrite dans la couche cognitive'},{name:'Obsidure',role:'Prépare un patch candidat, une sandbox, des tests et des preuves ; ne promeut rien seul.',status:'Fonction décrite dans la couche cognitive'},...names.map(name=>({name,role:'Contrat détaillé non fourni dans le catalogue. Voir le registre source.',status:'Mention documentaire du registre — référence probable'}))]:[]
 const current=organs.find(o=>o.name===selected)
 return <><p className="connection">Organes documentés · activité inconnue · autorité des organes : NONE</p>{error&&<p role="alert">{error}</p>}<main className="office-main"><section className="spatial-map" aria-label="Organes Obsidia"><div className="map-caption">COUCHE COGNITIVE <span>Population issue des sources</span></div><div className="rooms"><section className="room"><div className="room-sign"><h2>Brody · Obsidure · agents</h2><span>{organs.length} éléments documentés</span></div><div className="room-floor">{organs.map(o=><button className={`agent-token ${selected===o.name?'focused':''}`} key={o.name} onClick={()=>setSelected(o.name)}><span className="pixel-sprite" aria-hidden="true"/><strong>{o.name}</strong><small>Runtime non raccordé</small><span className="mission-bubble">{o.status}</span></button>)}</div></section></div><div className="map-caption">Aucune mission ou activité simulée</div></section><aside className="agent-inspector"><span className="eyebrow">ORGANE / FONCTION / FRONTIÈRES</span><h2>{current?.name||'Chargement'}</h2><p>{current?.role}</p><p className="declared">{current?.status}</p><dl><dt>Autorité</dt><dd>NONE · KX108_ONLY</dd><dt>Entrée / sortie détaillées</dt><dd>Non établies par cet index</dd><dt>Moteur actuel</dt><dd>Non vérifié</dd><dt>Mission, état et échanges actuels</dt><dd>Non observés</dd></dl>{source&&<><a className="source-link" href={`https://github.com/Eaubin08/obsidia-x108-proofs/blob/${source.commit}/${source.path}`} target="_blank" rel="noreferrer">Source exacte ↗</a><p>Index du 15 septembre 2026 · commit {source.commit.slice(0,12)}</p><details><summary>Texte source de la couche</summary><pre className="source-content">{source.content}</pre></details></>}</aside></main><section className="inventory-panel"><span className="eyebrow">MÉTHODE DE CONSTRUCTION / SOURCE</span><h2>Fonction → contrats → organe</h2><p>Connaissances qualifiées, politique d’incertitude, evidence, capacités autorisées et non-droits explicites. Le moteur cognitif est remplaçable.</p><p>La sortie canonique rejoint Aggregate / Meta / Evidence, puis X-108. Binder vérifie l’autorisation avant une action éventuelle ; receipt et replay tracent la chaîne.</p>{definition&&<details><summary>{definition.title}</summary><p>{definition.source}</p><pre className="source-content">{definition.body}</pre></details>}</section></>
}
