import {useEffect,useState} from 'react'
type Process={sessionId:string;active:boolean;runtimeActive:boolean;native:boolean;tool:string;output:string;title?:string}
export async function sessionAction(path:string,data:Record<string,unknown>={}){const r=await fetch('/obsidia-local/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw Error(d.error||'Action échouée');return d}
export default function SessionControls({selected,onSelect,waiting}:{selected:string;onSelect:(id:string)=>void;waiting:boolean}){
 const [processes,setProcesses]=useState<Process[]>([]),[text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[service,setService]=useState<{ready:boolean;reachable:boolean;error?:string;output?:string}|null>(null)
 useEffect(()=>{const c=new AbortController();let pending=false;const poll=async()=>{if(pending)return;pending=true;try{const r=await fetch('/obsidia-local/processes',{signal:c.signal});if(!r.ok)throw Error('Lecture des sessions impossible');setProcesses((await r.json()).processes);const sr=await fetch('/obsidia-local/services',{signal:c.signal});if(sr.ok)setService((await sr.json()).brody)}catch(e){if(!c.signal.aborted)setError(String(e))}finally{pending=false}};void poll();const t=setInterval(poll,1500);return()=>{c.abort();clearInterval(t)}},[])
 async function act(path:string,data:Record<string,unknown>={}){setBusy(true);setError('');try{const d=await sessionAction(path,data);if(d.sessionId)onSelect(d.sessionId);if(path.startsWith('input/'))setText('')}catch(e){setError(String(e))}finally{setBusy(false)}}
 const p=processes.find(p=>p.sessionId===selected)
 return <><p className="connection">API Brody : {service?.ready?'disponible':service?.reachable?'service inattendu sur le port 8000':'arrêtée — démarrage automatique au lancement de Brody'}</p>{busy&&<p role="status">Démarrage / action en cours…</p>}<details open className="inventory-panel"><summary>Lancer une session dans la page / test long</summary><div className="office-toolbar"><button disabled={busy} onClick={()=>act('run',{mode:'audit'})}>Audit Obsidure (dry-run)</button><button disabled={busy} onClick={()=>act('run',{mode:'audit-long'})}>Test long · 20 audits · ≥ 1 min</button>{[['obsidure','Obsidure'],['brody','Brody'],['cli','CLI Obsidia']].map(([id,label])=><button key={id} disabled={busy} onClick={()=>act('run',{mode:'interactive',tool:id})}>Session {label}</button>)}</div><p>Brody démarre son API si nécessaire et passe en mode non compact. Saisie et sortie dans la page. Les boutons du haut ouvrent les terminaux Windows.</p></details>{error&&<p role="alert">{error}</p>}{service?.error&&<details><summary>Erreur API Brody</summary><pre className="source-content">{service.output||service.error}</pre></details>}<div className="office-toolbar">{processes.map(p=><button key={p.sessionId} onClick={()=>onSelect(p.sessionId)}>{p.tool} · {p.sessionId.slice(0,8)}<small>{p.runtimeActive?(p.native?'Terminal Windows actif':'Session active'):p.active?'Programme terminé · fenêtre ouverte':'Terminé'}</small></button>)}</div>{p&&<div className="inventory-panel"><h3>Terminal · {p.tool} · {p.sessionId.slice(0,8)}</h3>{p.active&&<div className="office-toolbar">{p.native&&<button disabled={busy} onClick={()=>act('focus/'+p.sessionId)}>Aller au terminal Windows</button>}<button disabled={busy} onClick={()=>act('stop/'+p.sessionId)}>{p.native?'Fermer ce terminal':'Arrêter cette session'}</button></div>}{p.native&&<p>La saisie se fait dans la fenêtre Windows.</p>}{p.runtimeActive&&!p.native&&<form onSubmit={e=>{e.preventDefault();void act('input/'+p.sessionId,{text})}}><label>Ta demande / réponse<input aria-label="Ta demande" value={text} onChange={e=>setText(e.target.value)} disabled={!waiting||busy} maxLength={4096}/></label><button disabled={!waiting||busy||!text.trim()}>Envoyer</button>{!waiting&&<small>La saisie s’active lorsque ce processus attend une réponse.</small>}</form>}<pre className="source-content" aria-label="Sortie du terminal">{p.output||'En attente de sortie du processus…'}</pre></div>}</>
}
