import {useEffect,useState} from 'react'
import LayerExplorer from './LayerExplorer'
import ResearchOffice from './ResearchOffice'
import './App.css'
import './Office.css'
import './SourceOffice.css'
type Layer={id:string;title:string;content:string;path:string;branch:string;commit:string}
type Inventory={available:boolean;commit:string|null;branch:string|null;observedAt:string;agentFiles:string[];registry:{path:string;content:string}|null;error:string|null}
const registryNames=['Data','Provenance','Memory','EML','Energy','Timeverse','OCS','OC','Permission/Economic','OS3','Gencoin']
export default function SourceOffice(){
 const [layers,setLayers]=useState<Layer[]>([]);const [inventory,setInventory]=useState<Inventory|null>(null);const [selected,setSelected]=useState('10_COGNITIVE_SYSTEM');const [agent,setAgent]=useState('');const [view,setView]=useState(location.hash.replace('#','')||'agents');const [error,setError]=useState('');
 useEffect(()=>{const abort=new AbortController();fetch('/data/obsidia-layers.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}).then(d=>{if(!Array.isArray(d.layers))throw Error('Catalogue invalide');setLayers(d.layers)}).catch(e=>{if(!abort.signal.aborted)setError(String(e))});fetch('/data/local-inventory.json',{signal:abort.signal}).then(r=>r.ok?r.json():null).then(setInventory).catch(()=>{});const hash=()=>{setView(location.hash.replace('#','')||'agents');setAgent('')};window.addEventListener('hashchange',hash);return()=>{abort.abort();window.removeEventListener('hashchange',hash)}},[])
 const cognitive=layers.find(l=>l.id==='10_COGNITIVE_SYSTEM');const current=layers.find(l=>l.id===selected);const url=(l:Layer)=>`https://github.com/Eaubin08/obsidia-x108-proofs/blob/${l.commit}/${l.path}`;
 const overview=layers.filter(l=>['10','19','29','26'].includes(l.id.slice(0,2)));
 const files=inventory?.agentFiles.filter(p=>/\.(py|json|yaml|yml)$/.test(p)&&!p.includes('__pycache__'))||[];
 return <div className="observatory"><header className="obs-header"><a className="brand" href="#world">◈ OBSIDIA<small>UN MÊME ÉCOSYSTÈME / PLUSIEURS VUES</small></a><span className="authority">KX108_ONLY</span></header><nav className="view-nav">{[['world','Obsidia Monde','Où'],['workspace','Workspace','Quoi'],['agents','Pokémon View','Qui']].map(([id,name,hint])=><a key={id} href={`#${id}`} aria-current={view===id?'page':undefined}>{name}<small>{hint}</small></a>)}<a href="#agents" target="_blank" rel="noreferrer">↗ Pokémon View indépendante</a></nav>
 <section className="office-heading"><div><span className="eyebrow">{view==='agents'?'POPULATION DOCUMENTÉE':view==='workspace'?'ESPACE PROJET / SOURCES':'NAVIGATION DANS LES COUCHES'}</span><h1>{view==='agents'?'Bureau Pokémon R&D':view==='workspace'?'Workspace Obsidia':'Obsidia Monde'}</h1><p>{layers.length} couches chargées depuis tes sources · aucune saisie requise</p></div></section>
 <p className="connection">{inventory?.available?`Copie Git locale lue · ${inventory.branch} · ${inventory.commit?.slice(0,12)}`:'Catalogue documentaire chargé · copie Git locale non accessible ici'} · activité runtime non observée</p>{error&&<p role="alert">{error}</p>}
 {view==='agents'?<ResearchOffice/>:<><div className="organ-doors"><span>Organes / accès transversaux</span>{['Brody','Obsidure','CLI Obsidia','Jarjar','Jarvis'].map(name=><button key={name} onClick={()=>{setAgent(name);setSelected(name==='Brody'||name==='Obsidure'?'10_COGNITIVE_SYSTEM':'19_INTERFACE_WORKBENCH_VISUALIZATION')}}>{name}<small>{['Jarjar','Jarvis'].includes(name)?'Statué dans le plan':'Source documentaire'} · non raccordé</small></button>)}</div>
 <main className="office-main"><section className="spatial-map"><div className="map-caption">{view==='agents'?'BUREAU R&D':view==='workspace'?'DOSSIER PROJET':'CARTE DES COUCHES'}<span>Cliquer pour entrer</span></div><div className="rooms">
 {(view==='agents'?overview:layers).map((l,i)=><section className={`room ${selected===l.id?'selected-room':''}`} key={l.id} style={{'--room-hue':`${150+i*17}`} as React.CSSProperties}><button className="room-sign source-room" onClick={()=>{setSelected(l.id);setAgent('')}}><h2>{l.title.replace(/^\d+\s*[·•]\s*/,'')}</h2><span>↗ Entrer</span></button><div className="room-floor">
 {view==='agents'&&l.id==='10_COGNITIVE_SYSTEM'?registryNames.map(name=><button className="agent-token" key={name} onClick={()=>{setSelected(l.id);setAgent(name)}}><span className="pixel-sprite"/><strong>{name}</strong><small>Agent de couche mentionné</small><span className="mission-bubble">État runtime inconnu</span></button>):<button className="place-token" onClick={()=>{setSelected(l.id);setAgent('')}}><span className="building" aria-hidden="true">▥</span><strong>{view==='workspace'?'Sources / contexte du chantier':'Documents / composants'}</strong><small>{l.id}</small></button>}
 </div></section>)}
 </div></section><aside className="agent-inspector"><span className="eyebrow">{agent?'ÉLÉMENT SÉLECTIONNÉ':'LIEU SÉLECTIONNÉ'}</span><h2>{agent||current?.title||'Chargement'}</h2>{agent&&<p>{registryNames.includes(agent)?'Nom mentionné dans l’index du registre des agents. La mission, l’affectation réelle et l’activité ne sont pas établies par cet index.':agent==='Brody'?'Organe d’intégration sémantique : compréhension, contextualisation et formulation ; aucune autorité de décision.':agent==='Obsidure'?'Préparation de candidats, sandbox, tests et preuves ; aucune promotion autonome.':'Accès demandé dans ton plan ; lancement non raccordé.'}</p>}<p className="declared">Runtime : non connecté / activité inconnue</p>{current&&<><p>Branche : {current.branch}<br/>Commit : {current.commit.slice(0,12)}<br/>Document daté du 15 septembre 2026</p><a className="source-link" href={url(current)} target="_blank" rel="noreferrer">Source exacte ↗</a><details open={!agent}><summary>Lire le lieu / ses composants</summary><pre className="source-content">{current.content}</pre></details></>}{registryNames.includes(agent)&&cognitive&&<p className="muted">Provenance : AGENT_LAYER_REGISTRY_V0, mention dans la couche cognitive. Ce personnage représente cette mention documentaire.</p>}</aside></main>
 {view==='workspace'&&<section className="inventory-panel"><h2>Copie source locale · agents</h2><p>Lecture automatique du dépôt voisin au lancement. Aucun agent ni terminal n’est exécuté.</p>{inventory?.available?<><p>HEAD {inventory.commit} · {inventory.agentFiles.length} fichiers</p><div className="file-list">{files.map(p=><a key={p} href={`https://github.com/Eaubin08/obsidia-x108-proofs/blob/${inventory.commit}/${p}`} target="_blank" rel="noreferrer">{p}</a>)}</div>{inventory.registry&&<details><summary>Registre des agents lu dans la copie locale</summary><pre className="source-content">{inventory.registry.content}</pre></details>}</>:<p>Copie non accessible. Les sources documentaires restent consultables.</p>}<p className="muted">Tâches, processus, résultats et receipts live : raccordement restant à réaliser.</p></section>}
 {view==='workspace'&&<LayerExplorer/>}</>}<footer className="office-footer">Monde · Workspace · Pokémon View<span>Sources chargées / aucune activité simulée</span></footer></div>
}
